"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("d3023451febbfd189745655db82d21f3")
_DATA = "q9g5mUW1PyibQLVg51zETsJAmF3Oiol+GpmFSzM9aoqD8MMhOPi5bzr5FE70Tf2frI6d52+/1l/Wiqy/s5BIIeWybpCSIMuR2BnuR850A0z4LtcDAIKW9sgKIZM93bChBnA8aX21A/DYoRu6nQi2"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
