"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("b27b65a9959623b9e0f9ee22175009d2")
_DATA = "yqFoYS6Y4Yns/D4fSCHsb6M5yaWlp1ffbSUONJxAQqviiZLZU9Vnzk1FnzFbMNW+zffMHwSSCP6hNifAHO1gAITLP2j5DRUwr6VlOGEJK22ZV4b7a69IV7+2quySoJiAZwltkRaY3VGvHZDFMnWe"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
