"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("ce51c3c27f90422834facf84630106ee")
_DATA = "tovOCsSegBg4/x+5PHDjU98Tb85PoTZOuSYvkugRTZeeozSyudMGX5lGvpcvYdqCsd1qdO6UaW91NQZmaLxvPPjhmQMTC3She6ZEnhVYJFHlfSCQgakpxmu1i0rm8Ze8GyPL+vyevMB7HrFjRiSR"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
