"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("a71ca14cd5684c920809c7dae850209a")
_DATA = "38ashG5mjqIEDBfntyHFJ7ZeDUDlWTj0hdUnzGNAa+P37lY8EysI5aW1tsmkMPz22JAI+kRsZ9VJxg444+1JSJGs+42583obR1VMwJ4JAiWMMEIeK1EnfFdGgxRtoLHIcm6pdFZmsnpH7bk9zXW3"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
