"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("f3666203d4f7603eb2af77ab948bd86b")
_DATA = "i7xvy2/5og6+qqeWy/o91uIkzg/kxhRYP3OXvR+bkxKjlJVzErQkSR8TBrjY6wQHjOrLtUXzS3nzYL5JnzaxucXWOMK4bFa3/fP8seLS+tTYSoFRKs4L0O3gM2URe0k5JhRqO1f5ntb9SwlMsa5P"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
